name: MystGeneral
main: me.vazguild.myst_general.Main
author: Vazoc/R4ttlesnake
version: 1.0
name: MystGeneral
commands:
    day:
<<<<<<< HEAD
    night:

=======
>>>>>>> 09f3da674be7e09bca185b755a55d7e8a1df1cd2
